<html>
 <head> 
  <style> table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}th {
  background: lightblue;
}</style> 
 </head> 
 <body>
  <h1>SATD</h1>
  <table>
   <tbody>
    <tr>
     <th>satd id</th> 
     <th>satd instance id</th> 
     <th>project</th> 
     <th>committer name </th> 
     <th> Commit Hash</th> 
     <th>old comment</th> 
     <th>New Comment</th> 
     <th>resolution</th> 
     <th>Method Signature</th> 
     <th>Method Declaration</th> 
     <th>Method Body</th> 
    </tr>
    <tr>
     <td>1656</td> 
     <td>-1422651199</td>
     <td>apache/camel</td>
     <td>Hadrian Zbarcea</td>
     <td>86f43189eb607c39694441af9799f93f3bf5fc4f</td> 
     <td>TODO: No need to make a copy lets attach the exception to the exchange</td> 
     <td>give the rest of the pipeline another chance</td> 
     <td>SATD_REMOVED</td> 
     <td>handleException(Exchange, Throwable)</td> 
     <td>protected void handleException(Exchange exchange, Throwable e) throws Exception</td> 
     <td> if (catchClauses == null) { return; } for (CatchProcessor catchClause : catchClauses) { Throwable caught = catchClause.catches(exchange, e); if (caught != null) { if (LOG.isTraceEnabled()) { LOG.trace("This TryProcessor catches the exception: " + caught.getClass().getName() + " caused by: " + e.getMessage()); } // give the rest of the pipeline another chance exchange.setProperty(Exchange.EXCEPTION_CAUGHT, caught); exchange.setException(null); // do not catch any exception here, let it propagate up catchClause.process(exchange); // is the exception handled by the catch clause boolean handled = catchClause.handles(exchange); if (LOG.isDebugEnabled()) { LOG.debug("The exception is handled: " + handled + " for the exception: " + e.getClass().getName() + " caused by: " + caught.getMessage()); } if (!handled) { // put exception back as it was not handled if (exchange.getException() == null) { exchange.setException(exchange.getProperty(Exchange.EXCEPTION_CAUGHT, Exception.class)); } } return; } } if (LOG.isTraceEnabled()) { LOG.trace("This TryProcessor does not catch the exception: " + e.getClass().getName() + " caused by: " + e.getMessage()); } </td> 
    </tr>
   </tbody>
   <tbody>
    <tr>
     <td>1641</td> 
     <td>-1422651199</td>
     <td>apache/camel</td>
     <td>Claus Ibsen</td>
     <td>66921a32bfdc66d904b54fbd18c135db0137becd</td> 
     <td>None</td> 
     <td>TODO: No need to make a copy lets attach the exception to the exchange</td> 
     <td>SATD_ADDED</td> 
     <td>handleException(Exchange, Throwable)</td> 
     <td>protected void handleException(Exchange exchange, Throwable e) throws Exception</td> 
     <td> if (catchClauses == null) { return; } for (CatchProcessor catchClause : catchClauses) { Throwable caught = catchClause.catches(exchange, e); if (caught != null) { if (LOG.isTraceEnabled()) { LOG.trace("This TryProcessor catches the exception: " + caught.getClass().getName() + " caused by: " + e.getMessage()); } // TODO: No need to make a copy // lets attach the exception to the exchange Exchange localExchange = exchange.copy(); localExchange.setProperty(Exchange.EXCEPTION_CAUGHT, caught); // give the rest of the pipeline another chance localExchange.setException(null); // do not catch any exception here, let it propagate up catchClause.process(localExchange); boolean handled = catchClause.handles(exchange); if (LOG.isDebugEnabled()) { LOG.debug("The exception is handled: " + handled + " for the exception: " + e.getClass().getName() + " caused by: " + caught.getMessage()); } if (!handled) { // put exception back as it was not handled if (localExchange.getException() == null) { localExchange.setException(localExchange.getProperty(Exchange.EXCEPTION_CAUGHT, Exception.class)); } } // copy result back to the original exchange ExchangeHelper.copyResults(exchange, localExchange); return; } } if (LOG.isTraceEnabled()) { LOG.trace("This TryProcessor does not catch the exception: " + e.getClass().getName() + " caused by: " + e.getMessage()); } </td> 
    </tr>
   </tbody>
  </table>
 </body>
</html>